version: 2
jobs:
  build:
    working_directory: ~/locallibrary
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run:
          command: |
            source venv/bin/activate
            pip install -r requirements.txt
      - run:
          command: |
            python manage.py test
