version: 2
jobs:
  test:
    working_directory: ~/locallibrary
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run:
          command: |
            python manage.py test
